# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc25ecb7b8423139f9ce8705a5cbec3acb4f5bde63998769d16861c7c99a165c0b3ea4d767d6fe5a5023bae8409657ab01647b3df5d9508cc173b8bdd5dd7765

test:
  secret_key_base: ba96570749142f2db4df7f2975117e26d398a4c8b14717a9f1ec830887677a9fc46f6d4410de8834cfd459e8e0ea64b22978545e971bc47db34735b049b878a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
