# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html 
Resources:
  MyEC2:
    Type: "AWS::EC2::Instance"
    Properties: 
#      Affinity: String
#      AvailabilityZone: String
#      BlockDeviceMappings: 
#        - EC2 Block Device Mapping
#      DisableApiTermination: Boolean
#      EbsOptimized: Boolean
#      HostId: String
#      IamInstanceProfile: String
      ImageId: "ami-859bbfe2" # required
#      InstanceInitiatedShutdownBehavior: String
      InstanceType: "t2.micro"
#      Ipv6AddressCount: Integer
#      Ipv6Addresses:
#        - IPv6 Address Type
#      KernelId: String
#      KeyName: String
#      Monitoring: Boolean
#      NetworkInterfaces: 
#        - EC2 Network Interface"
#      PlacementGroupName: String
#      PrivateIpAddress: String
#      RamdiskId: String
#      SecurityGroupIds: 
#        - String
#      SecurityGroups: 
#        - String
#      SourceDestCheck: Boolean
#      SsmAssociations: 
#        - SSMAssociation
#      SubnetId: String
#      Tags: 
#        - Resource Tag
#      Tenancy: String
#      UserData: String
#      Volumes: 
#        - EC2 MountPoint
#      AdditionalInfo: String
